pring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:db_history}
  mongodb:
    username: ${MONGODB_USERNAME:root}
    password: ${MONGODB_PASSWORD:root}