server:
  port: 8091

spring:
  application:
    name: MS-HISTORY
  rabbitmq:
    host: localhost
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}

  data:
    mongodb:
      host: localhost
      port: ${MS_HISTORY_PORT:27017}
      database: ${MONGO_INITDB_DATABASE:db_ms-history}
      username: ${MONGO_INITDB_ROOT_USERNAME:root}
      password: ${MONGO_INITDB_ROOT_PASSWORD:root}
      authentication-database: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true