server:
  port: 9090
  servlet:
    context-path: /

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /ms-cars/v3/api-docs
        name: ms-cars
      - url: /ms-races/v3/api-docs
        name: ms-races
      - url: /ms-history/v3/api-docs
        name: ms-history
      - url: /ms-users/v3/api-docs
        name: ms-users

spring:
  profiles:
    active:
      - ${ACTIVE_SPRING_PROFILE:dev}
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MS-CARS
          uri: lb://MS-CARS
          predicates:
            - Path=/v1/cars/**,/ms-cars/v3/api-docs
          filters:
            - AuthenticationFilter


        - id: MS-HISTORY
          uri: lb://MS-HISTORY
          predicates:
            - Path=/v1/history/**,/ms-history/v3/api-docs
          filters:
            - AuthenticationFilter

        - id: MS-RACES
          uri: lb://MS-RACES
          predicates:
            - Path=/v1/races/**,/v1/tracks/**,/ms-races/v3/api-docs
          filters:
            - AuthenticationFilter

        - id: MS-USERS
          uri: lb://MS-USERS
          predicates:
            - Path=/v1/users/**,/ms-users/v3/api-docs



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

application:
  security:
    jwt:
      secret-key: 314E399266556A586E5272357528782F113F4528472B4B7250645367566B5570


