server:
  port: 9090

spring:
  application:
    name: API-GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

