server:
  port: 8090

spring:

  rabbitmq:
    host: localhost
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:guest}
    password: ${RABBITMQ_DEFAULT_PASS:guest}

  cloud:
    config:
      enabled: false

  data:
    mongodb:
      host: localhost
      port: ${MS_HISTORY_PORT:27018}
      database: ${MONGO_INITDB_DATABASE:db_ms-history}
      username: ${MONGO_INITDB_ROOT_USERNAME:root}
      password: ${MONGO_INITDB_ROOT_PASSWORD:root}
      authentication-database: admin

