server:
  port: 8090

spring:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      enabled: false

  data:
    mongodb:
      host: localhost
      port: 27017
      database: db_history
      username: root
      password: root
      authentication-database: admin

