version: "3.8"

services:
  ms-races:
    image: postgres
    container_name: ms-races
    restart: always
    environment:
      - POSTGRES_DB=db_races
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5434:5432

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672


