server:
  port: 8250
  servlet:
    context-path: /

openapi:
  service:
    title: ms-users
    version: 1.0.0
    url: http://localhost:9090
springdoc:
  api-docs:
    path: /ms-users/v3/api-docs
  swagger-ui:
    path: /ms-users/swagger-ui.html

spring:
  application:
    name: MS-USERS

  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${DB_USERS_PORT:5432}/${POSTGRES_DB:db_ms-users}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
    defer-datasource-initialization: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

application:
  security:
    jwt:
      secret-key: 314E399266556A586E5272357528782F113F4528472B4B7250645367566B5570

