version: "3.8"

services:
  ms-history:
    image: mongo
    container_name: ms-history
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=db_history
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017